#!/usr/bin/env bash
# script to print "Best School","bad luck" and "good luck" using while, if, elifand else.
i=1
while (( i <= 10 ))
do
    if [[ "$i" == '4' ]]; then
	echo "bad luck"
    elif [[ "$i" == '8' ]]; then
	echo "good luck"
    else
	echo "Best School"
    fi
   ((i++))
done
